config/routes.rb
Omrails::Application.routes.draw do
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'mission' => 'pages#mission'
  get 'links' => 'pages#links'

  root :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def action
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
			<%= link_to "Facebook", "http://google.com", class: "btn btn-primary btn-medium" %>
			<%= link_to "Twitter", "http://google.com", class: "btn btn-info btn-medium" %>
			<%= link_to "LinkedIn", "http://google.com", class: "btn btn-success btn-medium" %>
		</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <a class="brand" href="#">Zach's Website</a>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
	        <ul class="nav">
		        <li><%= link_to "Home", root_path %></li>
				<li><%= link_to "About", about_path %></li>
				<li><%= link_to "Mission", mission_path %></li>
				<li><%= link_to "Contact", contact_path %></li>
				<li><%= link_to "Links", links_path %></li>
			</ul>
			<ul class="nav pull-right">
		        <li><%= link_to "Login", "#" %></li>
				
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Zach's Site!!!</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
		<%= yield %>
		<%= render 'layouts/footer'%>	
	</div>
	
	</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/contact.html.erb
<h1>Contact</h1>

	<p>
		<%= link_to "Email Address", "zvannuccilee@gmail.com" %>
		<br></br>
		<br>
			Phone Number: 555-555-5555
		</br>
	</p>

app/views/pages/home.html.erb
<div class="hero-unit">
	<center>
		<h1> Welcome to My Website </h1>
		<br></br>
		<p>
			<img src="http://media.mcla.us/images/players/19006.jpg"/>
			<br></br>

			Take a look at me

			
		</p>

	</center>
</div>

app/views/pages/links.html.erb
<h1>links</h1>

	<p>
		<%= link_to "Google", "http://google.com" %>
	</p>

	<p>
		<%= link_to "Go Duck Go", "http://duckduckgo.com" %>

	</p>

app/views/pages/mission.html.erb
<h1>Mission</h1>